# Generated by Django 2.2.12 on 2021-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='outfits',
            field=models.ManyToManyField(through='data_api.Outfit_details', to='data_api.Outfit'),
        ),
    ]
