# Generated by Django 2.2.12 on 2021-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_auto_20210628_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hull',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='submunition_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
