# Generated by Django 2.2.12 on 2021-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_auto_20210820_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='shield_heat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
