# Generated by Django 2.2.12 on 2021-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0004_outfit_shield_heat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='active_cooling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='cooling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
