# Generated by Django 2.2.12 on 2021-08-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0006_outfit_atmosphere_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='cloak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
