# Generated by Django 2.2.12 on 2021-08-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0008_auto_20210822_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='capture_defense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
