# Generated by Django 2.2.12 on 2021-08-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0010_auto_20210822_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='stream',
            field=models.BooleanField(default=False),
        ),
    ]
