# Generated by Django 2.2.12 on 2021-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0011_auto_20210822_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='cluster',
            field=models.BooleanField(default=False),
        ),
    ]
