# Generated by Django 2.2.12 on 2021-10-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0012_auto_20210825_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='ammo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lauchners', to='data_api.Outfit'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='submunition_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_ammo', to='data_api.Outfit'),
        ),
    ]
