# Generated by Django 3.2.9 on 2021-11-16 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0013_auto_20211018_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hull',
            old_name='licenses',
            new_name='license',
        ),
        migrations.AlterField(
            model_name='outfit_details',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_details', to='data_api.build'),
        ),
    ]
