# Generated by Django 3.2.9 on 2021-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0015_auto_20211129_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='disruption_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='heat_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='hit_force_ps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outfit',
            name='hull_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='ion_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shield_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='slowing_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
