# Generated by Django 3.2.9 on 2021-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0016_auto_20211129_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shots_per_second',
            field=models.IntegerField(default=0),
        ),
    ]
