# Generated by Django 3.2.9 on 2021-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0018_alter_outfit_shots_per_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='hit_force_ps',
        ),
        migrations.AddField(
            model_name='outfit',
            name='anti_missile_per_second',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='hit_force_per_second',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
