# Generated by Django 3.2.9 on 2022-01-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0020_auto_20211206_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hull',
            old_name='max_guns',
            new_name='gun_ports',
        ),
        migrations.RenameField(
            model_name='hull',
            old_name='max_turrets',
            new_name='turret_mounts',
        ),
    ]
