# Generated by Django 3.2.9 on 2022-01-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0021_auto_20220112_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hull',
            old_name='max_drones',
            new_name='drone_bays',
        ),
        migrations.RenameField(
            model_name='hull',
            old_name='max_fighters',
            new_name='fighter_bays',
        ),
    ]
