# Generated by Django 3.2.9 on 2022-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0022_auto_20220112_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='hull',
            name='total_hp',
            field=models.IntegerField(default=0),
        ),
    ]
