# Generated by Django 3.2.9 on 2022-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0024_alter_hull_thrust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='thrust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
