# Generated by Django 3.2.9 on 2022-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0026_auto_20220116_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hull',
            name='active_cooling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='cloaking_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='cloaking_fuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='cooling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='cooling_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='energy_generation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='hull_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='hull_repair_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='reverse_thrust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='reverse_thrusting_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='reverse_thrusting_heat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='shield_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='shield_generation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='shield_heat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='thrust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hull',
            name='turn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='acceleration',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='active_cooling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='afterburner_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='afterburner_fuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='afterburner_heat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='afterburner_thrust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='cloaking_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='cloaking_fuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='cooling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='cooling_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='energy_consumption',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='energy_generation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='heat_generation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='ion_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='reload_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='reverse_thrust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='reverse_thrusting_energy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='reverse_thrusting_heat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='shield_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='shield_generation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='shield_heat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='solar_collection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='thrust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='turn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='turning_energy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='turning_heat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
