# Generated by Django 3.2.9 on 2022-01-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0030_rename_reload_time_outfit_reload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='disruption_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='slowing_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
