# Generated by Django 3.2.9 on 2022-01-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0031_auto_20220117_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='anti_missile_per_second',
            new_name='anti_missile_dps',
        ),
        migrations.AddField(
            model_name='outfit',
            name='afterburner_thrust_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='anti_missile_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='outfit',
            name='average_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='average_dps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='average_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='combined_cooling_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='disruption_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='outfit',
            name='energy_capacity_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='heat_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='hull_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='hull_repair_rate_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='outfit',
            name='ion_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='ramscoop_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='outfit',
            name='reverse_thrust_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shield_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shield_generation_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='slowing_dps_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='outfit',
            name='thrust_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='total_energy_generation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='outfit',
            name='total_energy_generation_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outfit',
            name='turn_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
