# Generated by Django 3.2.9 on 2022-01-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0032_auto_20220121_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='missile_capacity',
            new_name='ammo_capacity',
        ),
    ]
