# Generated by Django 3.2.9 on 2022-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0033_rename_missile_capacity_outfit_ammo_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='active_cooling_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='cooling_per_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
