# Generated by Django 3.2.16 on 2022-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0035_auto_20221125_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='hit_force',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
