# Generated by Django 3.2.16 on 2022-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0036_alter_outfit_hit_force'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='disruption_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
