# Generated by Django 3.2.16 on 2022-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0037_alter_outfit_disruption_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='turret_turn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
