# Generated by Django 3.2.16 on 2022-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0038_alter_outfit_turret_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hull',
            name='burn_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='corrosion_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='discharge_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='disruption_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='energy_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='fuel_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='hull_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='leak_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='piercing_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='shield_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hull',
            name='slowing_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hull',
            name='force_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hull',
            name='heat_protection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
