version: '3'

services:
  es-outfitter:
    image: thorndeux/es-outfitter:latest
    env_file:
      - ./.env.prod
    volumes: 
      - raw_data:/app/data_api/raw_data:rw
      - static_files:/app/es_outfitter/static:rw
      - db:/app/db:rw
    ports:
      - 8000:8000

  nginx:
    image: thorndeux/eso-nginx:latest
    volumes:
      - static_files:/home/app/web/staticfiles
    depends_on:
      - es-outfitter
    ports:
     - 80:80

volumes:
  raw_data:
  static_files:
  db: