version: '3'

services:
  es-outfitter:
    image: es-outfitter:dev
    container_name: es-outfitter-dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ./.env.dev
    volumes: 
      - ../:/app:rw
    ports: 
      - 8000:8000

  npm:
    image: frontend
    container_name: npm
    build:
      context: ../
      dockerfile: docker/npm/Dockerfile
    volumes:
      - ../frontend:/app:rw
    entrypoint: entrypoint.npm.sh
    command: npm run dev