# Docker image with mounted source files for development
ARG PYTHON_VERSION=3.11.0
ARG DEBIAN_VERSION=bullseye
FROM python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION}

ARG POETRY_VERSION=1.2.2

# Configure Poetry
ENV POETRY_VERSION=${POETRY_VERSION}
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache

# Install poetry separated from system interpreter
RUN python3 -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

# Add `poetry` to PATH
ENV PATH="${PATH}:${POETRY_VENV}/bin"

WORKDIR /app

# Install dependencies
COPY poetry.lock pyproject.toml ./
RUN poetry install

# Run your app
CMD [ "poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000" ]