name: build

on:
  push:
    branches:
      - 'develop'

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile.prod
          push: true
          tags: thorndeux/es-outfitter:latest
      - uses: docker/build-push-action@v3
        with:
          file: docker/nginx/Dockerfile
          context: "{{defaultContext}}:docker/nginx"
          push: true
          tags: thorndeux/eso-nginx:latest