name: deploy

on:
  workflow_run:
    workflows: [ build ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ESO_HOST }}
          username: ${{ secrets.ESO_USERNAME }}
          key: ${{ secrets.ESO_SSH_KEY }}
          source: "docker/docker-compose.prod.yml,docker/.env.prod"
          target: "/home/${{ secrets.ESO_USERNAME }}/es-outfitter"
          strip_components: 1
      - uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.ESO_HOST }}
          username: ${{ secrets.ESO_USERNAME }}
          key: ${{ secrets.ESO_SSH_KEY }}
          script: |
            docker compose -f /home/${{ secrets.ESO_USERNAME }}/es-outfitter/docker-compose.prod.yml down || true
            docker compose -f /home/${{ secrets.ESO_USERNAME }}/es-outfitter/docker-compose.prod.yml up
